### ISSUE TITLE
I2C address in table

### ISSUE THREAD

**Issue by motoGiS** [RobTillaart/AD524X#23]
Hello! Is the data in the "I2C address" table correct? AD0 and AD1 do not need to be swapped? In the datasheet AD1 is the high bit of the address.

**Comment by RobTillaart** [comment]
Thanks for the issue, 
You are referring to the table in the **readme.md** I assume..
Will look into it a.s.a.p.
Which version of the datasheet do you have? (a link is preferred)

**Comment by RobTillaart** [comment]
#### Analysis
AD5241, AD5242 datasheet REV C

AD0 is  bit 0
AD1 is bit 1

![image](https://github.com/RobTillaart/AD524X/assets/462844/a16e1ad3-c6dd-4d0b-86ce-576e034a1155)

Readme.md

![image](https://github.com/RobTillaart/AD524X/assets/462844/f4da2ce8-3d13-426c-baaa-768611d44ba8)

#### Conclusion
Yes you're right, will make a PR  later this week.
(there is a breaking change coming to improve the support for more boards. Need to redo the constructor / begin interface)

**Comment by motoGiS** [comment]
I didn't have time, you found it yourself :)

**Comment by RobTillaart** [comment]
I'm setting op a develop branch for the fix.

Thanks for pointing to this docu-bug.

**Comment by RobTillaart** [comment]
Any other remarks with respect to the library that need fix or changed?
(I might be able to include it in the same PR).

**Comment by motoGiS** [comment]
I will be testing the library in my project. Thank you for your efforts.

**Comment by RobTillaart** [comment]
Develop branch created and PR build is running.

**Comment by RobTillaart** [comment]
> I will be testing the library in my project. Thank you for your efforts.

Would be great if you can test the develop branch in your project,
Appreciated!
