### ISSUE TITLE
Measuring resistance of a digipot - A non manual alternative

### ISSUE THREAD

**Issue by thechordmaster** [RobTillaart/AD524X#28]
We are trying to cascade a bunch of i2c digipots including the AD5242X. Seeing that the tolerance is around 25-30%, we wanted to achieve a feedback/control loop that can measure the deviation in resistance and supplement it accordingly.

**Comment by RobTillaart** [comment]
There is no question or problem report relating to the AD524X library.
So I close this issue.

Better open a thread on the Arduino forum about the cascade project as these are not specific for this library.
There are more people there with possible new insights.
